sudo: false

language: java

jdk:
  - oraclejdk7

env:
  global:
    - secure: "XyqGJ+A/7aeR0JkMdjndaq+PqJc+dUxtzGMKlhAzt66RRGk9LKu2cpZt4Nn9uZ47/IaljtWBAj1rnllu6qrZj/rWLAZLfv2PLEVIMdcHjDYr/hl/O0TWrRrFamMTqcHQ1RMTS/bUh/kGgVgksgbzlYAeLIoYUuV4QYPOrITmvJa0MIrYy5yn1E4u6FC5ovclghH99ayRUCXYKb1+ecWHo/6qmD3u9leWP0EllZpLWiOoB65EpP+BOc3De9eOde91hrqh1fDEJ5Sbytj8s3YWWVDuKs1Tjqj+hNtKcoyrTevUdoXYfrVVnQ7Rpv9MwIzyMqZWNE4M41a4KBImnGpIT2o/Z/CwgECoH26envsTCg8BZtAq5g0EHacDdNMETminkAWLmirUg8YjMEKFy3BGS2Kzp4AtnkKiy+7EidMitpMeIcFJ9DKlJpHby0WAoMs/Sf+/+/AJEPISYJS6R/7qnp+7iGSwysWu4yIlIsqzyTdifN0sHyWjJNSyuosUN4Ai5/YknkZiVAEVoSfb+LoH398C6Qtf6V+jjDIoCK/elWrQinJcr7YN6u3iUwDoveQ1C5ka/SG+a3kvEu6lop7b2WuJ3NZOYD4noOiiqk2fDe+NxS1IuYt47BK2E0Ci3LRARWsHgxEkgrXPFkL4ezx5HrkIKlEJD8zNS531lQN9QmU="
	- # ^^ SONATYPE_USERNAME
	- secure: "BOacVsttusrpFDNwJOuGZ20X/h7s29/6HMIXZPwr4sshHild2CoHrG7qYj4W3ySn3P2QeOtIPjBL7Mh52lQbOUSpBxk9ZjTPYxuNNzOZsoVqTBLoIitIS1qgq3xaOj7UX0izdTNAadP70xY0cp9YC0u46zwDxRz41FTL+d7qXNA/tFSeI9Q2e+P+/MsLOMWXY0nRyOJo0GzwYNa+wwasv45dEJ/lhQj6IzUpXL9CG97oQqpz7XEQ/ccWJ8uoALNn8wqA7sd1iwTHpCFlJih5Nx/FqSwy+u1GPhLLG5jBBNO4nSpCfPEbvXByM81F4zrrkO90q45sQDZnyxxsY+oFltp6OFW4lkHkpOi9sDpqTHTHT23Fp7OfD6POUsdDXr9m4LjVN4Iu4/8PBq+phz4e5x3NuwMz0p+WSI8L+xe0tFPNrLPXKgpYuWQcnR9c6h9QEJVIayM8tuY0CwLebrrdTSs5VVSzKprDgNMwOSbPXN4u7wLTOeSBjTONsb6+SAexeB85A8hdxGKp8zDe3yYlyF48pzpy87zOoSb+gjtMnx4DGsUa1Jjji6E7rKb9duGonSaNRxr563LXwVwoHhu4XNoydbCyiT6tyzwUT07TPeWq9ZDj0gEOMJF7EjErgMgM5HxMbM5ZxI2adhT8FEowZfvurXKzVK2TUhkQiDwXZ54="
	- # ^^ SONATYPE_PASSWORD
	- secure: "2b14UxLHGKZLO/JtXU19Lv19EyLI1poj1OTj1kYyF7wQ8K65yaS++azwxl3ztE+sZqMSPJmZg6p/pjI12YRnF8JznQueOFOhRiSj5p0Y1UFIJT+9WToqmbC6M/wBErj51iA3/ge+icMrh02oxlSgJW2CCQliZ7sRkM5YSO7peWcnSNV6NHQQzAPoqidPMzrsa2PxMm1Dsk2Xy5dZKc54CSm8Yj/rnvsCgh3iznmLYVURmQoTayL7rBDzUQw8ouAobS+84iakpQ9zuY/C4UlGiW9sQ997p5H7NXru6qAAiJTGHtUrIrHVAZyKd55wVU11YoSox7PMpS4GzEbMnIjA6tN41QEb7Sg/M7opuPJirE4Sv1CIHI0/MNAHBezsX8w8yWkCb3QUm4iaID9J37kOwp/mgp3YBdVTG9rGRkdz4jCEMvyHe7MDMOZh+/n31/45HsIe/9OgDBRec95CW9XzxgxjVldu41p1FAZ3/zR9Btb6v2f31DD6Q1eIM1DpoOLhEGrgvlCbt2eT1pxDLiZzaXUpCLe3QNE4txQRmUzxP4eJlHF7m2j2HCuyACcQ6Vf2Hgrl9UhLLP6zILU5mQzN6dkmdBzsnN82A/yIVxnExaztoMAc/0uBML6DC0R1ubYa8tSTKS2y7x906L1Ry+rEut/3ZaCutWqpeksu2IAo+4s="
	- # ^^ GPG_KEY_NAME
	- secure: "r4+AaznlvZYdHLtzSB9wPUgFl2tVxLNA9LD5E5oNwjrpjnjWxD1ByA+nuZ2kjCHmTrlj1k6lvfZ5aGtfxDC/ST19Yb9Zg0m2ZXnJh8eZaqN/iRC+sU5WkjYCFoUOf+3O5pLqvxqerRYrYgbnDUQrudHvsbxk8/+btd7JCazqQXpMcUvlqqnYAM1IStaAJUbch38a1LHuKdL7Ycf6pCJwPHU7Jqf+456IbZ8wnkM7UitthNbb6wLfzy55ug/B8m9pJJj0q8l0JnXXJ3LYP95UcIrDbjigs7Z1tvhnJahQtmpcI4HIH/QuuixYXoSilQDIUxXlmRugrwL69CyPGtIXZvIkat2DGDgB981JFlb1m9EWOYxaw8+L++MAxEewZz7JrdeLXynsVGVVRKnjNNB7vd0SkzCGKcdW8QgAHhjEyy0jAj5U+agIlWfNZVT8q7cMVfvBexhc+uWCtQRarspgr968Jcem+E/LAXBnn27TbI73aAMCIETz7JD+kKCMtZGm0L5stsoy27xF2R/JZRwoQ7TsbiIVDS7TGspBLTlOUu4Y05CIocNtX0l0+Yu+qjy7gDFSKBMikoZQKcEx+OjKqtoc1ID9axorAZ9ksjyq9N8SYTCGhUXxeW1G2eNbalfwyt8bv+W43zi8QhBDcqMWpvTo7rPWeLHbRE9QA40j2sc="
	- # ^^ GPG_PASSPHRASE 
	
branches:
  only:
    - master
    - developer
    - /^release-.*$/      

install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -P !build-extras -B

cache:
	directories:
		- ~/.m2/repository

after_success:
	- ./scripts/before-deploy.sh
	- ./scripts/deploy.sh