language: java
sudo: false
jdk:
  - oraclejdk7

cache:
  directories:
    - ~/.m2/repository

env:
  global:
    - secure: XyqGJ+A/7aeR0JkMdjndaq+PqJc+dUxtzGMKlhAzt66RRGk9LKu2cpZt4Nn9uZ47/IaljtWBAj1rnllu6qrZj/rWLAZLfv2PLEVIMdcHjDYr/hl/O0TWrRrFamMTqcHQ1RMTS/bUh/kGgVgksgbzlYAeLIoYUuV4QYPOrITmvJa0MIrYy5yn1E4u6FC5ovclghH99ayRUCXYKb1+ecWHo/6qmD3u9leWP0EllZpLWiOoB65EpP+BOc3De9eOde91hrqh1fDEJ5Sbytj8s3YWWVDuKs1Tjqj+hNtKcoyrTevUdoXYfrVVnQ7Rpv9MwIzyMqZWNE4M41a4KBImnGpIT2o/Z/CwgECoH26envsTCg8BZtAq5g0EHacDdNMETminkAWLmirUg8YjMEKFy3BGS2Kzp4AtnkKiy+7EidMitpMeIcFJ9DKlJpHby0WAoMs/Sf+/+/AJEPISYJS6R/7qnp+7iGSwysWu4yIlIsqzyTdifN0sHyWjJNSyuosUN4Ai5/YknkZiVAEVoSfb+LoH398C6Qtf6V+jjDIoCK/elWrQinJcr7YN6u3iUwDoveQ1C5ka/SG+a3kvEu6lop7b2WuJ3NZOYD4noOiiqk2fDe+NxS1IuYt47BK2E0Ci3LRARWsHgxEkgrXPFkL4ezx5HrkIKlEJD8zNS531lQN9QmU=
    - # ^^ SONATYPE_USERNAME
    - secure: BOacVsttusrpFDNwJOuGZ20X/h7s29/6HMIXZPwr4sshHild2CoHrG7qYj4W3ySn3P2QeOtIPjBL7Mh52lQbOUSpBxk9ZjTPYxuNNzOZsoVqTBLoIitIS1qgq3xaOj7UX0izdTNAadP70xY0cp9YC0u46zwDxRz41FTL+d7qXNA/tFSeI9Q2e+P+/MsLOMWXY0nRyOJo0GzwYNa+wwasv45dEJ/lhQj6IzUpXL9CG97oQqpz7XEQ/ccWJ8uoALNn8wqA7sd1iwTHpCFlJih5Nx/FqSwy+u1GPhLLG5jBBNO4nSpCfPEbvXByM81F4zrrkO90q45sQDZnyxxsY+oFltp6OFW4lkHkpOi9sDpqTHTHT23Fp7OfD6POUsdDXr9m4LjVN4Iu4/8PBq+phz4e5x3NuwMz0p+WSI8L+xe0tFPNrLPXKgpYuWQcnR9c6h9QEJVIayM8tuY0CwLebrrdTSs5VVSzKprDgNMwOSbPXN4u7wLTOeSBjTONsb6+SAexeB85A8hdxGKp8zDe3yYlyF48pzpy87zOoSb+gjtMnx4DGsUa1Jjji6E7rKb9duGonSaNRxr563LXwVwoHhu4XNoydbCyiT6tyzwUT07TPeWq9ZDj0gEOMJF7EjErgMgM5HxMbM5ZxI2adhT8FEowZfvurXKzVK2TUhkQiDwXZ54=
    - # ^^ SONATYPE_PASSWORD
    - secure: "G7hF/7VknlplZZe1lzofDPRtfs+QmovZ3Cwmc/rLAN+NNmQflY+jX7NZV6Lj1KTs7O2l/sOXq+1NMyJieD5IVAIx68+PbFhkKMY9156bWn8JKCpcSY8x3wVSr90AM9x1yh1Epqy2H7MzsyB0aziQXo22abFS/wTSb15Wnvtz2kCr53P2jH9UbpUvssXks2amOSYq6h0YAbu79La0Knmqvks5uHKByl4TdaScumhOQW/eOgaa8FxBZLkCvIk3E8cwq6s3BvnI4xHaOrUc9Lx2f3bvU3wy6uOw4v5nVb0EetrkU6sXb9TpAmcQJykjQY3RNc98AS3sXWY3SPsV5CVQRNxvKeGjCvoIlwo0tZdFs6pQWhg0UwRXLLm0rtTQD3XU6c9pzfj93zKG1+wwE+BD63peEExnt799NvYx775zaQ8VkJS2GLt/uzA8vLylfT/9TuYkMb6kHdwDBxGmFjYk76ArrcQd54WG/eqZkp01Il13LjlpHbdF2TOOJYly1XAVqt4ll/aJcWNOsuIra77kCEhbewJ0i9N4oQyzxFgo7FTQaIlhspopg9TNgvFdiOGVDxD+9FCW0Ke3g1vlCOthEvghX3by3bUYmXubgGicA12DqAmzQHciuNuwCAo4Xsj4cq9Are/QxoEru9zGUgrEIcCIy6isYfwUzIiPPJ+8TPw=
    - # ^^ GPG_KEY_NAME
    - secure: "xfbFMA4u9Gn88/LHpVYRZypkdfvV+Vw9/IL/EDGaB9lzyy5oeSakh3YZZ/3hx8lgETHThavoMSJSfnUpP1KGZURJEq7YzwzjrpsKW2YRrXmuiH0c6YHFbF+Sa/DYJ6XHqcS779O8IUmgXLO1U7RTjsHI61xjU6Dt4jGEI/PSmHvh0e/TqZ4HsylPlIJAy9tpal0GQCdcx4PXCiXJqOVnZdyJz7ZeWImBP5Wx8ShaUyCHUo4T/VWLY84/baBEkRneDcvCDtfFTWkQc9MRHNVDwgA42PzJ3Mcn25Pbw+eZnebsrd0KXDUAd5LisnfRK0pq2HJKBA08+8K191seIkZVpeKswoD09WIdZ8MbDoe+ozklh+WZsletN/p+DpY0vYFZbXu4rXVuZL3RU1vcGMQmrku1/JKxIFdgtbqCFoXfEy0WSHZyEwVDMpJyymfDeFb/cooCmro93SimgwdQWBBNbHOSEsxxaBDpsefdi2SGgrFJM5Er3RSulyajv7qZcnElnHssnZHNilvPoVK9NuTFn1LKKZmbsJA9r2VeUxG6UQnHmigRzP3233Te4wRFLdATusO3QfEikvgy9u5YUzjQN4c4g4CztVAT+UHORYGE0LIDUOmbdXX+0/w/3VYcfeR8crmCCAskqBQrzEqVwP9HQZfL+KFKpV+VuxnsGVF9C8M=
    - # ^^ GPG_PASSPHRASE
   
branches:
  only:
    - master
    - developer
    - /^release-.*$/  

install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -P !build-extras -B
    
after_success:
  - ./scripts/deploy.sh
