language: java
jdk:
  - oraclejdk7
sudo: false
branches:
  only:
    - master
    - developer
    - /^release-.*$/
script: mvn clean verify
after_success:
    - mvn clean test jacoco:report coveralls:report