sudo: false

language: java

jdk:
  - oraclejdk7

env:
  global:
    - secure: "XyqGJ+A/7aeR0JkMdjndaq+PqJc+dUxtzGMKlhAzt66RRGk9LKu2cpZt4Nn9uZ47/IaljtWBAj1rnllu6qrZj/rWLAZLfv2PLEVIMdcHjDYr/hl/O0TWrRrFamMTqcHQ1RMTS/bUh/kGgVgksgbzlYAeLIoYUuV4QYPOrITmvJa0MIrYy5yn1E4u6FC5ovclghH99ayRUCXYKb1+ecWHo/6qmD3u9leWP0EllZpLWiOoB65EpP+BOc3De9eOde91hrqh1fDEJ5Sbytj8s3YWWVDuKs1Tjqj+hNtKcoyrTevUdoXYfrVVnQ7Rpv9MwIzyMqZWNE4M41a4KBImnGpIT2o/Z/CwgECoH26envsTCg8BZtAq5g0EHacDdNMETminkAWLmirUg8YjMEKFy3BGS2Kzp4AtnkKiy+7EidMitpMeIcFJ9DKlJpHby0WAoMs/Sf+/+/AJEPISYJS6R/7qnp+7iGSwysWu4yIlIsqzyTdifN0sHyWjJNSyuosUN4Ai5/YknkZiVAEVoSfb+LoH398C6Qtf6V+jjDIoCK/elWrQinJcr7YN6u3iUwDoveQ1C5ka/SG+a3kvEu6lop7b2WuJ3NZOYD4noOiiqk2fDe+NxS1IuYt47BK2E0Ci3LRARWsHgxEkgrXPFkL4ezx5HrkIKlEJD8zNS531lQN9QmU="
	- # ^^ SONATYPE_USERNAME
	- secure: "BOacVsttusrpFDNwJOuGZ20X/h7s29/6HMIXZPwr4sshHild2CoHrG7qYj4W3ySn3P2QeOtIPjBL7Mh52lQbOUSpBxk9ZjTPYxuNNzOZsoVqTBLoIitIS1qgq3xaOj7UX0izdTNAadP70xY0cp9YC0u46zwDxRz41FTL+d7qXNA/tFSeI9Q2e+P+/MsLOMWXY0nRyOJo0GzwYNa+wwasv45dEJ/lhQj6IzUpXL9CG97oQqpz7XEQ/ccWJ8uoALNn8wqA7sd1iwTHpCFlJih5Nx/FqSwy+u1GPhLLG5jBBNO4nSpCfPEbvXByM81F4zrrkO90q45sQDZnyxxsY+oFltp6OFW4lkHkpOi9sDpqTHTHT23Fp7OfD6POUsdDXr9m4LjVN4Iu4/8PBq+phz4e5x3NuwMz0p+WSI8L+xe0tFPNrLPXKgpYuWQcnR9c6h9QEJVIayM8tuY0CwLebrrdTSs5VVSzKprDgNMwOSbPXN4u7wLTOeSBjTONsb6+SAexeB85A8hdxGKp8zDe3yYlyF48pzpy87zOoSb+gjtMnx4DGsUa1Jjji6E7rKb9duGonSaNRxr563LXwVwoHhu4XNoydbCyiT6tyzwUT07TPeWq9ZDj0gEOMJF7EjErgMgM5HxMbM5ZxI2adhT8FEowZfvurXKzVK2TUhkQiDwXZ54="
	- # ^^ SONATYPE_PASSWORD
	- secure: "praX3AtGAPrp/vI3etkIw9GvXO4SVDK4Pqk9S1S+spwYebJr0Z4zDC+6MfLwADXQ1dfu0LY79tRRcP2uu5zFXJP8a1cxdMnO/ihrS1AO523FruhLxu7lygIhwMQ5TafaQro4rt6PjQ76npdkq/mc6GLLCDm/V8z8tX6KZJaQJmceQ7mvoB4b66uG1KSvKDFkSw0T2VhsA5SkOvBItg7/U30H5PZGyY/DJk2gJWXSGPWNr/uzQgMAjv3gtNaEkWFihxsie13cwd4cOXemeVFIJiCFQrU/4kWVzx/PVaMR0iEe7WpDfJhGa8Pb1NhQP2JdrIQ7xF9OTuIyLGKgUwd5xpYCggFyfb2+8dKy5NDsUcBZkjOGNmeNcprJ3Z2mSvxpyIxVFPaaRVkUD2Ah8PK4DFfbFg+4BRlRkgpRfpMXtIiHFs8SQ9jCVukB0YxLnPNIAm44F8pxRtjJIxONzxTIDOXquYypxK0yQyX5VdISgCQVOwp+7PyPBRHuWuaFcBR7ukGJHornwZt/gC4hFaRBiOhHTHm+m0S+7oQ9j8rCHJc+tMrzCD+tapcSB1GQwmY5yQ+vcDft/X30fF41G5HFchKQe5f23g/xlcL8/O4qJW4ZP+Hqk9FwclqTv8NUW7K8frAPLHe2Sz0GfFq0qXygRpm9OHSyFPkzrxDnYBk5cO0="
	- # ^^ GPG_KEY_NAME
	- secure: "r4+AaznlvZYdHLtzSB9wPUgFl2tVxLNA9LD5E5oNwjrpjnjWxD1ByA+nuZ2kjCHmTrlj1k6lvfZ5aGtfxDC/ST19Yb9Zg0m2ZXnJh8eZaqN/iRC+sU5WkjYCFoUOf+3O5pLqvxqerRYrYgbnDUQrudHvsbxk8/+btd7JCazqQXpMcUvlqqnYAM1IStaAJUbch38a1LHuKdL7Ycf6pCJwPHU7Jqf+456IbZ8wnkM7UitthNbb6wLfzy55ug/B8m9pJJj0q8l0JnXXJ3LYP95UcIrDbjigs7Z1tvhnJahQtmpcI4HIH/QuuixYXoSilQDIUxXlmRugrwL69CyPGtIXZvIkat2DGDgB981JFlb1m9EWOYxaw8+L++MAxEewZz7JrdeLXynsVGVVRKnjNNB7vd0SkzCGKcdW8QgAHhjEyy0jAj5U+agIlWfNZVT8q7cMVfvBexhc+uWCtQRarspgr968Jcem+E/LAXBnn27TbI73aAMCIETz7JD+kKCMtZGm0L5stsoy27xF2R/JZRwoQ7TsbiIVDS7TGspBLTlOUu4Y05CIocNtX0l0+Yu+qjy7gDFSKBMikoZQKcEx+OjKqtoc1ID9axorAZ9ksjyq9N8SYTCGhUXxeW1G2eNbalfwyt8bv+W43zi8QhBDcqMWpvTo7rPWeLHbRE9QA40j2sc="
	- # ^^ GPG_PASSPHRASE 
	
branches:
  only:
    - master
    - developer
    - /^release-.*$/      

after_success:
	- mvn jacoco:report coveralls:report
    - mvn deploy -DskipTests=true --settings setting-maven.xml