language: java
sudo: false
jdk:
- oraclejdk7
cache:
  directories:
  - "~/.m2/repository"
branches:
  only:
  - master
  - developer
  - "/^release-.*$/"
install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -P !build-extras -B
after_success:
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in ./deploy/pubring.gpg.enc -out ./deploy/pubring.gpg -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in ./deploy/secring.gpg.enc -out ./deploy/secring.gpg -d
- "./scripts/deploy.sh"
env:
  global:
  - GPG_DIR="`pwd`/deploy"